name: auto-merge 

on:
  workflow_run:
    types:
      - completed
    workflows:
      - 'ci'

permissions:
  pull-requests: write
  contents: write

jobs:
  auto-merge:
    name: auto-merge-dependabot 
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.actor == 'dependabot[bot]' }}
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1.1.1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Enable auto-merge for Dependabot PRs
        if: ${{!contains(steps.metadata.outputs.dependency-names, 'maven-plugin-api') && steps.metadata.outputs.update-type == 'version-update:semver-minor'}}
        run: gh pr merge --auto --rebase "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

